export enum NodeType {
    Combat = 'combat',
    CombatBoss = 'combat_boss',
    CombatElite = 'combat_elite',
    CombatStandard = 'combat_standard',
    Camp = 'camp',
    CampHouse = 'camp_house',
    CampRegular = 'camp_regular',
    Portal = 'portal',
    Encounter = 'encounter',
    Merchant = 'merchant',
    RoyalHouse = 'royal_house',
    RoyalHouseA = 'royal_house_a',
    RoyalHouseB = 'royal_house_b',
    RoyalHouseC = 'royal_house_c',
    RoyalHouseD = 'royal_house_d',
    Empty = 'empty',
    Event = 'event',
    Treasure = 'treasure',
}
