version: '3'
name: kote-gameplay-stack
services:
    mongodb:
        container_name: kote-mongodb
        image: mongo:6.0
        restart: always
        ports:
            - '27017:27017'
        volumes:
            - mongodb-data:/data/db
        networks:
            - kote-network
    core:
        container_name: kote-core
        build: .
        restart: always
        env_file:
            - .env
        ports:
            - '${APP_PORT:-3000}:3000'
        depends_on:
            - mongodb
        networks:
            - kote-network

networks:
    kote-network:
        external: true

volumes:
    mongodb-data:
