version: '3'
services:
    core:
        container_name: kote-core
        build:
            context: .
            dockerfile: Dockerfile
        image: 121760970575.dkr.ecr.us-east-1.amazonaws.com/blightfell-development:latest
        restart: always
        ports:
            - '${DOCKER_APP_PORT:-3000}:${APP_PORT:-3000}'
        networks:
            - kote-network
        env_file:
            - .env
networks:
    kote-network:
        external: true