version: '3'
services:
    mongodb:
        image: mongo:6.0
        restart: always
        ports:
            - '27017:27017'
        volumes:
            - mongodb-data:/data/db
        networks:
            - kote-net
    nestjs-api:
        build: .
        restart: always
        env_file:
            - .env
        ports:
            - '${APP_PORT:-3000}:3000'
        depends_on:
            - mongodb
        networks:
            - kote-net

networks:
    kote-net:
        driver: bridge

volumes:
    mongodb-data:
