version: '3'
name: kote-gameplay-stack
services:
    mongodb:
        container_name: kote-mongodb
        image: mongo:6.0
        ports:
            - '27017:27017'
        volumes:
            - mongodb-data:/data/db
        networks:
            - kote-network
    mysql:
        container_name: kote-mysql
        image: mysql:latest
        ports:
            - '3306:3306'
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: 12345
            MYSQL_ROOT_PASSWORD: 12345
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - kote-network
    core:
        container_name: kote-core
        build: .
        env_file:
            - .env
        ports:
            - '${APP_PORT:-3000}:3000'
        depends_on:
            - mongodb
            - mysql
        networks:
            - kote-network

networks:
    kote-network:
        external: true

volumes:
    mongodb-data:
    mysql-data:
