version: '3'
services:
    mongodb:
        container_name: kote-mongodb
        image: mongo:6.0
        restart: always
        ports:
            - '27017:27017'
        volumes:
            - ./data:/data/db
        networks:
            - kote-network
    core:
        container_name: kote-core
        build:
            context: .
            dockerfile: Dockerfile
        image: 121760970575.dkr.ecr.us-east-1.amazonaws.com/blightfell-development:v0.0.1
        restart: always
        env_file:
            - .env
        ports:
            - '${DOCKER_APP_PORT:-3000}:${APP_PORT:-3000}'
        networks:
            - kote-network
    web:
        container_name: kote-web
        build:
            context: ../kote-game-react
            dockerfile: Dockerfile
        image: blightfell-web
        restart: always
        env_file:
            - .env
        ports:
            - '8080:8080'
        networks:
            - kote-network
networks:
    kote-network:
        external: true
