import { EnemyGroupTypeEnum } from '../expedition/expedition.enum';
import { EnemyGroup } from './enemyGroups.schema';

export const enemiesDataSeed: EnemyGroup[] = [
    {
        act: 1,
        groupNumber: 1,
        chance: 25,
        type: EnemyGroupTypeEnum.standard,
        enemies: ['StingFae1', 'StingFae2'],
        stepMin: 0,
        stepMax: 2,
    },
    {
        act: 1,
        groupNumber: 2,
        chance: 25,
        type: EnemyGroupTypeEnum.standard,
        enemies: ['BarkCharger', 'BarkCharger'],
        stepMin: 0,
        stepMax: 2,
    },
    {
        act: 1,
        groupNumber: 3,
        chance: 25,
        type: EnemyGroupTypeEnum.standard,
        enemies: ['SporeMonger'],
        stepMin: 0,
        stepMax: 2,
    },
    {
        act: 1,
        groupNumber: 4,
        chance: 25,
        type: EnemyGroupTypeEnum.standard,
        enemies: ['MimicFrog'],
        stepMin: 0,
        stepMax: 2,
    },
    {
        act: 1,
        groupNumber: 5,
        chance: 12,
        type: EnemyGroupTypeEnum.standard,
        enemies: ['MimicFrog1', 'MimicFrog2'],
        stepMin: 3,
        stepMax: null,
    },
    {
        act: 1,
        groupNumber: 6,
        chance: 11,
        type: EnemyGroupTypeEnum.standard,
        enemies: ['GroundMoth'],
        stepMin: 3,
        stepMax: null,
    },
    {
        act: 1,
        groupNumber: 7,
        chance: 10,
        type: EnemyGroupTypeEnum.standard,
        enemies: ['StingFae1', 'StingFae2', 'SwampGoblin1'],
        stepMin: 3,
        stepMax: null,
    },
    {
        act: 1,
        groupNumber: 8,
        chance: 10,
        type: EnemyGroupTypeEnum.standard,
        enemies: ['BarkCharger', 'BarkCharger', 'BarkCharger'],
        stepMin: 3,
        stepMax: null,
    },
    {
        act: 1,
        groupNumber: 9,
        chance: 10,
        type: EnemyGroupTypeEnum.standard,
        enemies: ['SwampGoblin2', 'SwampGoblin2', 'SwampGoblin1'],
        stepMin: 3,
        stepMax: null,
    },
    {
        act: 1,
        groupNumber: 10,
        chance: 10,
        type: EnemyGroupTypeEnum.standard,
        enemies: ['SporeMonger', 'Trapelican'],
        stepMin: 3,
        stepMax: null,
    },
    {
        act: 1,
        groupNumber: 11,
        chance: 9,
        type: EnemyGroupTypeEnum.standard,
        enemies: ['MimicFrog'],
        stepMin: 3,
        stepMax: null,
    },
    {
        act: 1,
        groupNumber: 12,
        chance: 9,
        type: EnemyGroupTypeEnum.standard,
        enemies: ['BarkCharger', 'SwampGoblin2'],
        stepMin: 3,
        stepMax: null,
    },
    {
        act: 1,
        groupNumber: 13,
        chance: 9,
        type: EnemyGroupTypeEnum.standard,
        enemies: ['StingFae', 'StingFae', 'StingFae', 'StingFae'],
        stepMin: 3,
        stepMax: null,
    },
    {
        act: 1,
        groupNumber: 14,
        chance: 8,
        type: EnemyGroupTypeEnum.standard,
        enemies: ['StingFae1', 'GroundMoth', 'StingFae2'],
        stepMin: 3,
        stepMax: null,
    },

    {
        act: 1,
        groupNumber: 1,
        chance: 33.3,
        type: EnemyGroupTypeEnum.elite,
        enemies: ['ThornWolf'],
        stepMin: 3,
        stepMax: null,
    },
    {
        act: 1,
        groupNumber: 2,
        chance: 33.3,
        type: EnemyGroupTypeEnum.elite,
        enemies: ['QueenOrchid'],
        stepMin: 3,
        stepMax: null,
    },
    {
        act: 1,
        groupNumber: 3,
        chance: 33.3,
        type: EnemyGroupTypeEnum.elite,
        enemies: ['AncientOne'],
        stepMin: 3,
        stepMax: null,
    },
];
