import { Injectable } from '@nestjs/common';
import { ReturnModelType } from '@typegoose/typegoose';
import { InjectModel } from 'kindagoose';
import { Seeder } from 'nestjs-seeder';
import { ContestMap } from './contestMap.schema';
import {
    addHoursToDate,
    countSteps,
    findStepWithMostNodes,
    setHoursMinutesSecondsToUTCDate,
} from 'src/utils';
import { ContestService } from '../contest/contest.service';
import { MapBuilderService } from '../map/builder/mapBuilder.service';
import { createMoreOrEquals12NodesMap, createLess12NodesMap, createLess5NodesMap } from '../map/builder/actOne.config';
import { SettingsService } from '../components/settings/settings.service';

@Injectable()
export class ContestMapSeeder implements Seeder {
    constructor(
        @InjectModel(ContestMap)
        private readonly contestMap: ReturnModelType<typeof ContestMap>,
        private readonly mapBuilderService: MapBuilderService,
        private readonly contestService: ContestService,
        private readonly settingsService: SettingsService,
    ) {}

    public defaultName = 'Default Contest Map';

    async seed(): Promise<any> {
    
        const { maxAutogeneratedMapSteps, maxAutogeneratedMapNodes } =
            await this.settingsService.getSettings();
        
        let map;

        if(maxAutogeneratedMapSteps >= 12){
            map = await this.mapBuilderService.createMap({
                actConfig: createMoreOrEquals12NodesMap(maxAutogeneratedMapSteps, maxAutogeneratedMapNodes),
                makeAvailable: true
            });
        }else if(maxAutogeneratedMapSteps < 12 && maxAutogeneratedMapSteps >= 5){
            map = await this.mapBuilderService.createMap({
                actConfig: createLess12NodesMap(maxAutogeneratedMapSteps, maxAutogeneratedMapNodes),
                makeAvailable: true
            });
        }else{
            //- maxAutogeneratedMapSteps minor 5
            map = await this.mapBuilderService.createMap({
                actConfig: createLess5NodesMap(maxAutogeneratedMapSteps, maxAutogeneratedMapNodes),
                makeAvailable: true
            });
        }

        // Here we calculate how many steps we have in the map
        const maxSteps = maxAutogeneratedMapSteps;
        const maxNodes = findStepWithMostNodes(map);

        const contestMap = await this.contestMap.create({
            name: this.defaultName,
            nodes: map,
            maxSteps,
            maxNodes,
            isGenerated: true,
        });

        const today = new Date();
        const availableAt = setHoursMinutesSecondsToUTCDate(today);
        const endsAt = setHoursMinutesSecondsToUTCDate(
            availableAt,
            23,
            59,
            59,
            999,
        );
        const validUntil = addHoursToDate(endsAt, 6);

        const event_id = await this.contestService.getLastEventId();

        // Now we schedule the contest to the day
        await this.contestService.create({
            map_id: contestMap.id,
            event_id: event_id + 1,
            available_at: availableAt,
            ends_at: endsAt,
            valid_until: validUntil,
        });

        return contestMap;
    }

    async drop(): Promise<any> {
        await this.contestService.deleteMany({});
        return await this.contestMap.deleteMany({});

        // const today = new Date();
        // const availableAt = setHoursMinutesSecondsToUTCDate(today);
        // const endsAt = setHoursMinutesSecondsToUTCDate(
        //     availableAt,
        //     23,
        //     59,
        //     59,
        //     999,
        // );

        // const mapFound = await this.contestService.findOne({
        //     name: this.defaultName,
        //     created_at: { $gte: availableAt },
        //     ends_at: { $lte: endsAt }
        // });

        // if (mapFound) {
        //     await this.contestService.deleteMany({map_id: mapFound.id });
        //     return await this.contestMap.deleteMany({ _id: mapFound.id });
        // }
        // return;
    }
}
